import type { Exercise } from '@/types'

export const SEED_EXERCISES: Omit<Exercise, 'id'>[] = [
  // ─── PETTO ────────────────────────────────────────────────────────────────
  { name: 'Panca Piana Bilanciere', muscles: ['petto'], secondaryMuscles: ['tricipiti', 'spalle'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Panca Inclinata Bilanciere', muscles: ['petto'], secondaryMuscles: ['tricipiti', 'spalle'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Panca Declinata Bilanciere', muscles: ['petto'], secondaryMuscles: ['tricipiti'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Panca Piana Manubri', muscles: ['petto'], secondaryMuscles: ['tricipiti', 'spalle'], equipment: 'dumbbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Panca Inclinata Manubri', muscles: ['petto'], secondaryMuscles: ['tricipiti', 'spalle'], equipment: 'dumbbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Croci Piana Manubri', muscles: ['petto'], secondaryMuscles: [], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Croci Inclinata Manubri', muscles: ['petto'], secondaryMuscles: [], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Crossover Cavi', muscles: ['petto'], secondaryMuscles: [], equipment: 'cable', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Push-Up', muscles: ['petto'], secondaryMuscles: ['tricipiti', 'spalle'], equipment: 'bodyweight', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Chest Press Macchina', muscles: ['petto'], secondaryMuscles: ['tricipiti'], equipment: 'machine', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Dip Petto', muscles: ['petto'], secondaryMuscles: ['tricipiti', 'spalle'], equipment: 'bodyweight', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Pec Deck Macchina', muscles: ['petto'], secondaryMuscles: [], equipment: 'machine', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },

  // ─── SCHIENA ──────────────────────────────────────────────────────────────
  { name: 'Stacco da Terra', muscles: ['schiena'], secondaryMuscles: ['glutei', 'femorali', 'trapezio'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Trazioni', muscles: ['schiena'], secondaryMuscles: ['bicipiti'], equipment: 'bodyweight', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Lat Machine Avanti', muscles: ['schiena'], secondaryMuscles: ['bicipiti'], equipment: 'cable', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Lat Machine Dietro', muscles: ['schiena'], secondaryMuscles: ['bicipiti'], equipment: 'cable', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Rematore Bilanciere', muscles: ['schiena'], secondaryMuscles: ['bicipiti', 'trapezio'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Rematore Manubrio', muscles: ['schiena'], secondaryMuscles: ['bicipiti'], equipment: 'dumbbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Rematore Cavo Basso', muscles: ['schiena'], secondaryMuscles: ['bicipiti'], equipment: 'cable', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Pullover Manubrio', muscles: ['schiena'], secondaryMuscles: ['petto'], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Facepull', muscles: ['schiena'], secondaryMuscles: ['spalle'], equipment: 'cable', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Iperextension', muscles: ['schiena'], secondaryMuscles: ['glutei'], equipment: 'bodyweight', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Shrug Bilanciere', muscles: ['trapezio'], secondaryMuscles: [], equipment: 'barbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Shrug Manubri', muscles: ['trapezio'], secondaryMuscles: [], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'T-Bar Row', muscles: ['schiena'], secondaryMuscles: ['bicipiti'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Macchina Rematore', muscles: ['schiena'], secondaryMuscles: ['bicipiti'], equipment: 'machine', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },

  // ─── SPALLE ───────────────────────────────────────────────────────────────
  { name: 'Military Press Bilanciere', muscles: ['spalle'], secondaryMuscles: ['tricipiti'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Lento Avanti Manubri', muscles: ['spalle'], secondaryMuscles: ['tricipiti'], equipment: 'dumbbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Alzate Laterali Manubri', muscles: ['spalle'], secondaryMuscles: [], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Alzate Laterali Cavi', muscles: ['spalle'], secondaryMuscles: [], equipment: 'cable', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Alzate Frontali Manubri', muscles: ['spalle'], secondaryMuscles: [], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Alzate Posteriori Manubri', muscles: ['spalle'], secondaryMuscles: [], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Alzate Posteriori Cavi', muscles: ['spalle'], secondaryMuscles: [], equipment: 'cable', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Arnold Press', muscles: ['spalle'], secondaryMuscles: ['tricipiti'], equipment: 'dumbbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Shoulder Press Macchina', muscles: ['spalle'], secondaryMuscles: ['tricipiti'], equipment: 'machine', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },

  // ─── BRACCIA ──────────────────────────────────────────────────────────────
  { name: 'Curl Bilanciere', muscles: ['bicipiti'], secondaryMuscles: ['avambracci'], equipment: 'barbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Curl Manubri Alternato', muscles: ['bicipiti'], secondaryMuscles: ['avambracci'], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Curl Martello', muscles: ['bicipiti'], secondaryMuscles: ['avambracci'], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Curl Cavo Basso', muscles: ['bicipiti'], secondaryMuscles: [], equipment: 'cable', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Curl Concentrato', muscles: ['bicipiti'], secondaryMuscles: [], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Curl su Panca Scott', muscles: ['bicipiti'], secondaryMuscles: [], equipment: 'barbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Tricipiti Panca Stretta', muscles: ['tricipiti'], secondaryMuscles: ['petto'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'French Press', muscles: ['tricipiti'], secondaryMuscles: [], equipment: 'barbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Pushdown Tricipiti', muscles: ['tricipiti'], secondaryMuscles: [], equipment: 'cable', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Overhead Tricipiti Cavo', muscles: ['tricipiti'], secondaryMuscles: [], equipment: 'cable', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Kick Back Tricipiti', muscles: ['tricipiti'], secondaryMuscles: [], equipment: 'dumbbell', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Dip Tricipiti', muscles: ['tricipiti'], secondaryMuscles: ['petto', 'spalle'], equipment: 'bodyweight', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },

  // ─── GAMBE ────────────────────────────────────────────────────────────────
  { name: 'Squat', muscles: ['quadricipiti'], secondaryMuscles: ['glutei', 'femorali'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Squat Frontale', muscles: ['quadricipiti'], secondaryMuscles: ['glutei'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Leg Press', muscles: ['quadricipiti'], secondaryMuscles: ['glutei', 'femorali'], equipment: 'machine', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Leg Extension', muscles: ['quadricipiti'], secondaryMuscles: [], equipment: 'machine', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Affondi', muscles: ['quadricipiti'], secondaryMuscles: ['glutei', 'femorali'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Affondi Manubri', muscles: ['quadricipiti'], secondaryMuscles: ['glutei', 'femorali'], equipment: 'dumbbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Bulgarian Split Squat', muscles: ['quadricipiti'], secondaryMuscles: ['glutei', 'femorali'], equipment: 'dumbbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Leg Curl Sdraiato', muscles: ['femorali'], secondaryMuscles: [], equipment: 'machine', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Leg Curl Seduto', muscles: ['femorali'], secondaryMuscles: [], equipment: 'machine', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Romanian Deadlift', muscles: ['femorali'], secondaryMuscles: ['glutei', 'schiena'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Romanian Deadlift Manubri', muscles: ['femorali'], secondaryMuscles: ['glutei'], equipment: 'dumbbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Hip Thrust', muscles: ['glutei'], secondaryMuscles: ['femorali'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Glute Bridge', muscles: ['glutei'], secondaryMuscles: ['femorali'], equipment: 'bodyweight', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Cable Kickback', muscles: ['glutei'], secondaryMuscles: [], equipment: 'cable', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Calf Raise in Piedi', muscles: ['polpacci'], secondaryMuscles: [], equipment: 'machine', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Calf Raise Seduto', muscles: ['polpacci'], secondaryMuscles: [], equipment: 'machine', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Hack Squat', muscles: ['quadricipiti'], secondaryMuscles: ['glutei'], equipment: 'machine', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Sumo Deadlift', muscles: ['femorali'], secondaryMuscles: ['glutei', 'quadricipiti'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },

  // ─── CORE ─────────────────────────────────────────────────────────────────
  { name: 'Plank', muscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Crunch', muscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Russian Twist', muscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Leg Raise', muscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Ab Wheel', muscles: ['core'], secondaryMuscles: ['schiena'], equipment: 'other', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Cable Crunch', muscles: ['core'], secondaryMuscles: [], equipment: 'cable', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Hollow Hold', muscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Side Plank', muscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', category: 'isolation', isCustom: false, createdAt: new Date().toISOString() },

  // ─── CARDIO / FULL BODY ───────────────────────────────────────────────────
  { name: 'Rematore Orizzontale', muscles: ['schiena'], secondaryMuscles: ['bicipiti', 'core'], equipment: 'machine', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Clean & Jerk', muscles: ['schiena'], secondaryMuscles: ['spalle', 'quadricipiti', 'glutei'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Snatch', muscles: ['schiena'], secondaryMuscles: ['spalle', 'quadricipiti'], equipment: 'barbell', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
  { name: 'Kettlebell Swing', muscles: ['glutei'], secondaryMuscles: ['femorali', 'schiena', 'core'], equipment: 'other', category: 'compound', isCustom: false, createdAt: new Date().toISOString() },
]
